name: PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  verify_title:
    name: Verify Title
    runs-on: ubuntu-latest
    if: ${{github.event.action != 'edited' || github.event.changes.title}}
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Run Commitlint
        run: echo "${{github.event.pull_request.title}}" | npx commitlint
